Table_Tag_Priya_work
Pawan1005/MI-10-MEAN pull request #108
Opened 2021-02-22 12:46 UTC by priyaughade

2021-02-24 07:34 UTC, MKadeer17 approved these changes

2021-02-24 09:47 UTC, dnyaneshwarkhule approved these changes

2021-02-26 08:27 UTC, Pawan1005 requested changes
remove extra spaces form files and add title

2021-02-26 08:27 UTC, Pawan1005 commented on priya/HTML/PriyaAssign4Q3.html
> +
add title

2021-02-26 09:04 UTC, MKadeer17 commented on priya/HTML/PriyaAssign4Q3.html
> +
Priya add title tag

2021-03-02 09:14 UTC, priyaughade commented on priya/HTML/PriyaAssign4Q3.html
> +
Already Added

2021-03-05 06:19 UTC, dnyaneshwarkhule approved these changes

2021-03-08 03:34 UTC, MKadeer17 approved these changes

2021-03-08 06:45 UTC, merged