Uploading Assignment10.html
Pawan1005/MI-10-MEAN pull request #197
Opened 2021-03-18 04:01 UTC by khushboochauhan107

2021-03-18 07:46 UTC, Pawan1005 requested changes

2021-03-18 07:46 UTC, Pawan1005 commented on KHUSHBOO/Assingments/Assignment10.html
> +      <img src="/home/khushboo/Downloads/img.jpeg">
use relative path

2021-03-18 10:17 UTC, poonam-khode approved these changes

2021-03-19 03:48 UTC, MKadeer17 approved these changes

2021-03-19 04:02 UTC, mayank30041995 approved these changes

2021-03-30 03:17 UTC, MKadeer17 approved these changes

2021-03-30 10:00 UTC, Pawan1005 approved these changes

2021-03-30 10:02 UTC, merged