uploading /MI-10-MEAN/Pratiksha/Javascript assignment
Pawan1005/MI-10-MEAN pull request #240
Opened 2021-04-11 11:22 UTC by pratikshaghule

2021-04-12 04:32 UTC, poonam-khode requested changes
proper structure and remove extra space

2021-04-15 03:45 UTC, poonam-khode approved these changes

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q1.html
> +
remove extra line and proper structure

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q1.html
> +
remove extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q1.html
> +
same as 2 Comment

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q1.html
> +
same as

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q1.html
> +
same as

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q1.html
> +
same as 1 comment

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q3.html
> +<head>
proper structure

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q3.html
> +    }</script>
what need double close Script

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q4.html
> +
remove extra line and proper structure please

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q4.html
> +
what is this Pratikaha please remove all extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q5.html
> +<head>
proper structure

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q5.html
> +
remove extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment4/Q5.html
> +
remove extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment5/Q1.html
> +
remove extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment5/Q1.html
> +
remove extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment5/Q4.html
> +
remove extra line

2021-04-15 05:36 UTC, VIP5614 commented on Pratiksha/Javascript/Assignment5/Q5.html
> +
remove extra line

2021-04-16 10:47 UTC, KomalShinde813 requested changes

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Bootstrap/Assignment5/Assignment5.html
> +
remove extra lines

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Bootstrap/Assignment5/Assignment5.html
> +</html>
add extra line at the end of file

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment2/Q1.html
> +    <script></script>
incomplete program don't push incomplete work on git

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment2/Q2.html
> +    <title>Document</title>
change title in every assignment

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment2/Q2.html
> +      var c;
use proper variable name don't use a, b, c, d, x, y, z

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment2/Q2.html
> +        if (c >= 75 && c <= 100) {
no need of curly brackets for single if condition

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q1.html
> +          document.getElementById("demo").innerText = `  Not Leap year`;
remove extra space

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q1.html
> +        event.preventDefault();
what is the use of this line?

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q2 .html
> +
remove extra line spaces

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q2 .html
> +
remove extra lines from everywhere

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q2 .html
> +                <input type="button" value="Check" onClick="p()">
change function name

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q2 .html
> +    </script>
check indentation properly

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q2 .html
> +</html>
extra line required at the end of file

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q3.html
> +      n = document.getElementById("val1").value;
change variable name

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q3.html
> +        if (n / 2 == 0) {
no need of curly brackets for single if condition

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q_2.html
> +        function p() {
change function name

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment3/Q_2.html
> +<!DOCTYPE html>
duplicate program

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        var n,m;
space required after ,

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +      function automorphic(){
space required before {

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        n = parseInt(document.getElementById ("first").value);
remove  extra space

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        m = n*n;
space required in operators

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        if(n%10 != m%10)
space required in operators and after if

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        document.getElementById('demo1').innerHTML = n +" is not an atomorphic number";
check indentation

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        document.getElementById('demo1').innerHTML = n +" is an automorphic number";
check indentation

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q2.html
> +        event.preventDefault();
what is the use of this line here?

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q3.html
> +        var num,i,p,r,sum=0,save_num;
space required after ,

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q3.html
> +            i=1;
space required before and after operator make this change everywhere

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q3.html
> +</html>
extra line required at the end of file

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q4.html
> +<head>
check indentation <head> is under <html>

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q4.html
> +        switch(x){
space required

2021-04-16 10:47 UTC, KomalShinde813 commented on Pratiksha/Javascript/Assignment4/Q4.html
> +            case "A":
add a here in || condition and remove duplicate code

2021-04-16 11:06 UTC, sanketmod approved these changes

2021-04-19 05:10 UTC, VIP5614 approved these changes

2021-04-20 07:52 UTC, pratikshaghule commented on Pratiksha/Javascript/Assignment3/Q1.html
> +        event.preventDefault();
to hold on the screen

2021-04-20 07:52 UTC, pratikshaghule commented on Pratiksha/Javascript/Assignment3/Q3.html
> +      n = document.getElementById("val1").value;
okk

2021-04-20 11:00 UTC, pratikshaghule commented on Pratiksha/Javascript/Assignment4/Q3.html
> +</html>
done

2021-04-21 08:51 UTC, closed without merging