JsAssignment6
Pawan1005/MI-10-MEAN pull request #251
Opened 2021-04-19 05:57 UTC by priyaughade

2021-04-19 06:27 UTC, MKadeer17 approved these changes

2021-04-19 06:27 UTC, MKadeer17 commented on priya/javascript/JsAssign6Q1.html
> +<head>
Indentation Little bit
```suggestion
    <head>
```

2021-04-19 06:27 UTC, MKadeer17 commented on priya/javascript/JsAssign6Q1.html
> +<body>
Same here 4 space before body tag
```suggestion
    <body>
```

2021-04-19 06:27 UTC, MKadeer17 commented on priya/javascript/JsAssign6Q2.html
> +<head>
Same here in head and body tag

2021-04-19 06:27 UTC, MKadeer17 commented on priya/javascript/JsAssign6Q3.html
> +<head>
Same here, every page indentation

2021-04-21 04:59 UTC, poonam-khode approved these changes

2021-04-21 11:41 UTC, MKadeer17 approved these changes

2021-04-21 12:25 UTC, SnehaMakade requested changes
do check the files, u have pushed 98 files, push only vch is for the js assignment6 remove extra files.

2021-04-23 04:34 UTC, saifsyed566 requested changes

2021-04-23 04:34 UTC, saifsyed566 commented on priya/Bootstrap/Assignment1/Bootstrap1.html
> +<head>
head tag indentation is missing

2021-04-23 04:34 UTC, saifsyed566 commented on priya/Bootstrap/Assignment1/Bootstrap1.html
> +<body>
body tag indentation

2021-04-23 04:34 UTC, saifsyed566 commented on priya/Bootstrap/Assignment1/Bootstrap1.html
> +        </div>
<div>tag indentation is incorrect
```suggestion
</div>
```

2021-04-23 10:55 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q1.html
> +            var b,a,result;
change variable names  in all files like input 1 and input 2 it acn not be a or b.

2021-04-23 10:56 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q1.html
> +     </script>
there should be four tab space in between parent and child tags so correct the indentation.

2021-04-23 10:56 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q1.html
> +    </html>
and new end line and do correct the indentation.

2021-04-23 10:57 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q2.html
> +<html lang="en">\
remove extra operator after closing bracket of html

2021-04-23 10:58 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q2.html
> +        Name2: <input type="text" id="name2" placeholder="Enter first name " />
if its anme 2 then change the placeholder accordingly.

2021-04-23 10:58 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q2.html
> +        Name5: <input type="text" id="name5" placeholder="Enter first name " />
change the placeholder like enter fifth name

2021-04-23 10:59 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q2.html
> +            document.write("<b> The Input Names stored in array : <b> ");
there  should be no space before colon add space after colon only.

2021-04-23 11:00 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q2.html
> +            document.write("<b> The Input Names joined with ~ :<b> ");
add space after colon and remove extra space

2021-04-23 11:02 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q3.html
> +        Number 1: <input type="text" id="num1" placeholder="Enter first Number "> <br>
remove extra space in all numbers field before " this.

2021-04-23 11:03 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q3.html
> +                var b,a,c,d,e,cancel,joined, arr;
change variable names and there should be always a space after a comma so add it and make a change of variable

2021-04-23 11:03 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q3.html
> +    </html>
add new end line

2021-04-23 11:04 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +        Number 1: <input type="text" id="num1" placeholder="Enter first number "> <br>
remove extra space in all numbers filed

2021-04-23 11:05 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +                var b,a,c,d,e,fact, arr;
change the variable names and add a space after comma

2021-04-23 11:05 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +                a= parseInt(document.getElementById("num1").value);
there should be always a space before and after operator so make this everywhere except in html tags

2021-04-23 11:06 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +                arr=[a,b,c,d,e]
add space after comma

2021-04-23 11:06 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +                var sum=0;
add space after and before all operator in all files

2021-04-23 11:07 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +    </html>
add new end line

2021-04-23 11:08 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q5.html
> +                    // for (var i=0 ; i<=sum1.length-1; i++ ){
do not push commented code

2021-04-23 11:08 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q5.html
> +  </html>
add new end line in all files

2021-04-23 11:08 UTC, SnehaMakade commented on priya/javascript/JsAssign6Q1.html
> +<head>
make a proper indentation

2021-04-23 11:09 UTC, SnehaMakade commented on priya/javascript/JsAssign6Q1.html
> +
remove extra line and space also

2021-04-23 11:09 UTC, SnehaMakade commented on priya/javascript/JsAssign6Q1.html
> +
remove extra lines

2021-04-23 11:10 UTC, SnehaMakade commented on priya/javascript/JsAssign6Q2.html
> +<head>
indentation should be proper in all files

2021-04-23 11:11 UTC, SnehaMakade requested changes
do the changes in all files, changes of variable names removing of extra space and lines and do proper indentation in all files

2021-04-23 13:01 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q1.html
> +</html>
add end line in all files

2021-04-23 13:02 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q2.html
> +                document.write("Input Names with Assending order  : <br>");
there should be no space befor colon remove the space before colon

2021-04-23 13:03 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q3.html
> +                for (var i=0; i<=4; i++){
add a space before and after operator in all files

2021-04-23 13:15 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q3.html
> +</html>
add end line

2021-04-23 13:16 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +</html>
add end line in all files and add a space after and before each operator

2021-04-23 13:16 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q5.html
> +            var sum,arr,fact;
add a space after comma and colon in each file

2021-04-23 13:16 UTC, SnehaMakade commented on priya/javascript/Assignment6/JsAssign6Q5.html
> +                                document.write(sum1);
dont push commented code on git.remove it

2021-04-23 13:17 UTC, SnehaMakade requested changes
do the changes

2021-04-27 03:10 UTC, Snehal-113 requested changes

2021-04-27 03:10 UTC, Snehal-113 commented on priya/javascript/Assignment6/JsAssign6Q1.html
> +</html>
Not getting the expected output.Either take 5 text fields or 5 times prompt and then display the output

2021-04-27 03:10 UTC, Snehal-113 commented on priya/javascript/Assignment6/JsAssign6Q1.html
> +</html>
indentation is not done properly.use prettier

2021-04-27 03:10 UTC, Snehal-113 commented on priya/javascript/Assignment6/JsAssign6Q2.html
>  </html>
need to accept names till the user presses cancel in prompt dialog box and not only 5

2021-04-27 03:10 UTC, Snehal-113 commented on priya/javascript/Assignment6/JsAssign6Q4.html
> +</html>
same change as mentioned in teh above program

2021-04-27 03:10 UTC, Snehal-113 commented on priya/javascript/Assignment6/JsAssign6Q5.html
> +</html>
same change

2021-04-28 06:20 UTC, Snehal-113 approved these changes

2021-04-28 06:56 UTC, saifsyed566 approved these changes

2021-04-28 09:51 UTC, merged