Uploading my Assignment-5 to Assignment-6
Pawan1005/MI-10-MEAN pull request #253
Opened 2021-04-20 05:18 UTC by VIP5614

2021-04-20 05:22 UTC, pratikshaghule approved these changes

2021-04-20 07:41 UTC, poonam-khode approved these changes

2021-04-20 07:54 UTC, sanketmod approved these changes

2021-04-20 12:51 UTC, avinash0070 requested changes
Change title to File Added : Assignment_5 and Assignment_6

2021-04-20 13:08 UTC, avinash0070 requested changes
assign yourself

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +</html>
bad code indentation need 4 space

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-5/Sum-match.html
> +</html>
Add new line

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-5/Sum-match.html
> +    <p id="p"></p>
give proper name to this id

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +            secondNumber = 1;
where is declare  secondNumber variable

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-5/Sum-match.html
> +        let n = document.getElementById("no").value;
give proper name to this variable

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-5/Sum-match.html
> +<!DOCTYPE html>
bad code indentation

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-6/list-of-name.html
> +                let namesList = document.getElementById('namesList');
use 4 space only

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +</html>
add new line

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-6/sumFactorial.html
> +<!DOCTYPE html>
need proper code indentation

2021-04-20 13:08 UTC, avinash0070 commented on Vish/JS/Assignment-7/words-and-whitespaces.html
> +<!DOCTYPE html>
bad code indentation

2021-04-20 13:13 UTC, avinash0070 reviewed
need proper code indentation to all files

2021-04-21 07:24 UTC, VIP5614 commented on Vish/JS/Assignment-5/Sum-match.html
> +</html>
done

2021-04-21 07:24 UTC, VIP5614 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +            secondNumber = 1;
done

2021-04-21 07:24 UTC, VIP5614 commented on Vish/JS/Assignment-5/Sum-match.html
> +    <p id="p"></p>
done

2021-04-21 07:25 UTC, VIP5614 commented on Vish/JS/Assignment-5/Sum-match.html
> +<!DOCTYPE html>
done

2021-04-21 07:25 UTC, VIP5614 commented on Vish/JS/Assignment-6/list-of-name.html
> +                let namesList = document.getElementById('namesList');
done

2021-04-21 07:25 UTC, VIP5614 commented on Vish/JS/Assignment-6/string.html
> +</html>
done

2021-04-21 07:25 UTC, VIP5614 commented on Vish/JS/Assignment-6/sumFactorial.html
> +<!DOCTYPE html>
done

2021-04-21 07:26 UTC, VIP5614 commented on Vish/JS/Assignment-7/words-and-whitespaces.html
> +<!DOCTYPE html>
proper code indentation done

2021-04-21 07:51 UTC, avinash0070 requested changes

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extr line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/list-of-name.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/list-of-name.html
> +
Remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/list-of-name.html
> +      } */
Remove commented code

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-7/Number_Palindrom.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-7/Number_Palindrom.html
> +<html>
need proper code indentation

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-7/words-and-whitespaces.html
> +    <center><button onClick="WordCount()">CHECK</button></center>
change CHECK to Check

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/sumNumber.html
> +
Remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/sumNumber.html
> +
Remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/sumNumber.html
> +
Remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Sum-match.html
>  </html>
Add new line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
Remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
>  </html>
add new line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-5/Fibonacci-Series.html
> +
Remove this extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/everyNumberFactorial.html
> +<!DOCTYPE html>
add proper code indentation

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/list-of-name-Ascending&Descending.html
> +<!DOCTYPE html>
need proper code indatation

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
Remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
remove extra line

2021-04-21 07:51 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
> +
remove extra line

2021-04-21 08:35 UTC, avinash0070 requested changes

2021-04-21 08:35 UTC, avinash0070 commented on Vish/JS/Assignment-6/string.html
>  </html>
add new line

2021-04-21 08:43 UTC, VIP5614 commented on Vish/JS/Assignment-6/string.html
>  </html>
Done

2021-04-21 08:49 UTC, avinash0070 approved these changes

2021-04-21 09:01 UTC, merged