New::Syed_Assaignment9
Pawan1005/MI-10-MEAN pull request #254
Opened 2021-04-20 05:38 UTC by saifsyed566

2021-04-20 07:22 UTC, MKadeer17 approved these changes

2021-04-20 11:47 UTC, harshalkotkar approved these changes

2021-04-21 04:42 UTC, Pawan1005 requested changes
add new line at the end of file
indentation is missing

2021-04-21 04:42 UTC, Pawan1005 commented on syedsaif/JavaScript/Day6/Task.html
> +</html>
add new line at the end of file 
indentation is missing

2021-04-28 01:55 UTC, Snehal-113 requested changes
change the file names like Assignment1Q1 or Assign1Q1,Assign1Q2
it becomes easy for tracking

2021-05-02 08:58 UTC, merged