Poonam@work
Pawan1005/MI-10-MEAN pull request #258
Opened 2021-04-21 10:31 UTC by poonam-khode

2021-04-21 11:13 UTC, sanketmod approved these changes

2021-04-22 08:52 UTC, pratikshaghule approved these changes

2021-04-23 04:29 UTC, VIP5614 approved these changes

2021-04-23 04:36 UTC, VIP5614 approved these changes

2021-04-23 11:17 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que2.html
> +        Enter Names : <input type="text" id="a">
remove space before colon, there should be always a space after colon and comma  not before

2021-04-23 11:18 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que3.html
> +          document.getElementById("demo").innerHTML = "The sum is " + sum;
remove extra space

2021-04-23 11:22 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que5.html
> +                }
correct the indentation closing bracket should be in the same position where function or if else starts

2021-04-23 11:23 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que5.html
> +                var newarray = [];
long variable names should be like new_array like this so make this change in files where long variables are declared

2021-04-23 11:23 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que5.html
> +                    let p = n;
change the varable name

2021-04-23 11:24 UTC, SnehaMakade commented on poonam/JS/Assignment7_js/que1.html
> +                    var n, i, j;
change the varable names

2021-04-23 11:25 UTC, SnehaMakade commented on poonam/JS/Assignment7_js/que2.html
> +            var n, temp;
n should not be the variable name change it

2021-04-23 11:26 UTC, SnehaMakade requested changes
do changes as per comments given correct the variable names in all files.

2021-04-23 12:40 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que3.html
> +            let n = prompt('Enter a Number:');
change the variable name

2021-04-23 12:41 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que2.html
> +        <button onclick="add()">display</button>
button title should start with capital letter

2021-04-23 12:41 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que4.html
> +          let n = prompt('Enter a Number:');
change the variable name

2021-04-23 12:42 UTC, SnehaMakade commented on poonam/JS/Assignment6_js/que4.html
> +        var n = input.length;
vaiable should not be a single letter

2021-04-23 12:45 UTC, SnehaMakade commented on poonam/JS/Assignment7_js/que4.html
> +            n = prompt("Enter number of students:");
change the variable name

2021-04-23 12:47 UTC, SnehaMakade commented on poonam/JS/Assignment9_js/que1.html
> +        <title>que 1</title>
it would be good if u can change the title according the assignment so correct the title in all files

2021-04-23 12:47 UTC, SnehaMakade commented on poonam/JS/Assignment9_js/que1.html
> +            var n = parseInt(prompt("Enter a number:"));
change the variable

2021-04-23 12:48 UTC, SnehaMakade commented on poonam/JS/Assignment9_js/que2.html
> +            var n = parseInt(prompt("Enter a number: "));
variable name?

2021-04-23 12:48 UTC, SnehaMakade commented on poonam/JS/Assignment9_js/que2.html
> +                    var p = n.toString().split("").reverse().join("");
change the variable name

2021-04-23 12:49 UTC, SnehaMakade commented on poonam/JS/Assignment9_js/que2.html
> +                    console.log(p);
do not push console.log on git. remove console.log from all files.

2021-04-23 12:50 UTC, SnehaMakade commented on poonam/JS/Assignment9_js/que4.html
> +            var n = prompt("Enter a string: ");
change the variable name of n and p

2021-04-23 12:50 UTC, SnehaMakade requested changes
change variable names and remove console

2021-04-27 12:19 UTC, Snehal-113 requested changes

2021-04-27 12:19 UTC, Snehal-113 commented on poonam/JS/Assignment9_js/que5.html
> +                const doubleletter = (arr = []) => {
you have used arrow function.There is no need for array function here

2021-04-27 12:19 UTC, Snehal-113 commented on poonam/JS/Assignment9_js/que5.html
>      </body>
just need to check adjacent letters.For eg tomorrow : r is double letter, boss : s is the double letter, bottom : t is the double letter

2021-04-28 06:12 UTC, Snehal-113 approved these changes

2021-04-28 06:14 UTC, merged