Pratiksha work
Pawan1005/MI-10-MEAN pull request #261
Opened 2021-04-22 09:08 UTC by pratikshaghule

2021-04-23 04:02 UTC, VIP5614 approved these changes

2021-04-23 05:17 UTC, poonam-khode approved these changes

2021-04-23 07:13 UTC, sanketmod approved these changes

2021-04-26 13:24 UTC, Snehal-113 requested changes

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment7/Q2.html
> +
This progam is  not giving the desired output, please check it.

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment7/Q4.html
> +        for (var mark = 0; mark < 5; mark++) {
why there is a need of for within a for, if i enter number of students,it is reading marks for 35 students

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment7/Q5.html
> +      for (var i = 0; i < stdCount; i++) {
need to correct

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment9/Q1.html
> +      }
for the number u need to use the / and % logic

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment9/Q3.html
> +
program is not giving me the correct ouput. Please debug the program

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment9/Q4.html
>        const value = checkPalindrome(string);
this value is never printed in the program, so i don't get the output

2021-04-26 13:24 UTC, Snehal-113 commented on Pratiksha/Javascript/Assignment9/Q5.html
> +</html>
not getting the correct output.Also the output is displayed on console and not on web page

2021-04-30 07:24 UTC, closed without merging