javascript assignment 7
Pawan1005/MI-10-MEAN pull request #264
Opened 2021-04-26 05:38 UTC by harshalkotkar

2021-04-26 05:54 UTC, MKadeer17 approved these changes

2021-04-28 01:10 UTC, Snehal-113 requested changes

2021-04-28 01:10 UTC, Snehal-113 commented on HARSHAL/javascript/assignment7/assignment7Q4.html
> +            for (var i = 0; i < marks.length; i++) {
for (var i = 0; i < marks.length-1; i++)

2021-04-28 01:10 UTC, Snehal-113 commented on HARSHAL/javascript/assignment7/assignment7Q5.html
> +                marks[j + 1] = current;
logic not working properly

2021-04-28 06:15 UTC, Snehal-113 approved these changes

2021-04-28 06:18 UTC, merged