New code added: js assignment 8
Pawan1005/MI-10-MEAN pull request #269
Opened 2021-04-28 08:45 UTC by poonam-khode

2021-04-28 10:56 UTC, sanketmod requested changes

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que1.html
> +        <title>que 1</title>
change title

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que2.html
> +    <title>Document</title>
Change title

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que3.html
> +        <title>que 3</title>
Change title

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que1.html
> +            function myFunction(item, index) {
Why are you creating a function if you are using forEach() method

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que3.html
> +                var temp;
the logic for selection sort is wrong you are using bubble sort logic

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que4.html
> +        <script>
don't write entire logic in head section

2021-04-28 10:56 UTC, sanketmod commented on poonam/JS/Assignment8_js/que4.html
> +    <body>
Format document properly

2021-04-28 11:00 UTC, MKadeer17 approved these changes

2021-04-29 05:12 UTC, sanketmod approved these changes

2021-04-29 13:50 UTC, Snehal-113 approved these changes

2021-04-29 13:50 UTC, Snehal-113 commented on poonam/JS/Assignment8_js/que3.html
> +                    bubblesort();
the array needs to be passed as parameter to all the sorting algo functions.
bubblesort(arrMarks);

2021-04-29 13:50 UTC, Snehal-113 commented on poonam/JS/Assignment8_js/que3.html
> +            function bubblesort() {
bubblesort(arrMarks){

2021-04-29 13:58 UTC, merged