Assingment_4 & Assingment 13 completed
Pawan1005/MI-10-MEAN pull request #282
Opened 2021-05-03 15:21 UTC by omerana14

2021-05-04 03:30 UTC, MKadeer17 approved these changes
Add indentation in Assignment 13 All Files.

2021-05-04 07:25 UTC, poonam-khode approved these changes

2021-05-05 13:03 UTC, Snehal-113 requested changes

2021-05-05 13:03 UTC, Snehal-113 commented on Ome/JavaScript/Assignment 13/JavaScriptAssignment13_Q1.html
> +            let otherDate = new Date("02-21-2012 03:12");
need to convert this date into local timestamp-use toLocaleString() function.check it's implementation

2021-05-05 13:03 UTC, Snehal-113 commented on Ome/JavaScript/Assignment 13/JavaScriptAssignment13_Q2.html
> +
or u can write weekday=["SU","MO","TU"......,"SA"];

2021-05-05 13:03 UTC, Snehal-113 commented on Ome/JavaScript/Assignment 13/JavaScriptAssignment13_Q3.html
> +            var twoDaysAgo = d.getDate(x) - 2;  //change day here
two should not be hard coded, if the user enters 1 day before or 5days before it must the show the date, this logic is not working if i give 1/5/2020

2021-05-06 11:01 UTC, omerana14 commented on Ome/JavaScript/Assignment 13/JavaScriptAssignment13_Q1.html
> +            let otherDate = new Date("02-21-2012 03:12");
function manualTime() {
            var d = new Date("Feb 21,2021 03:12:00");
            var n = d.toLocaleString('en-US', { year: "numeric", day: "numeric", month: "short", hour: "numeric", minute: "numeric", hour12: true });
            window.alert("Local Time & Date " + n);
        }


I use this logic here and now code works fine

2021-05-06 11:02 UTC, omerana14 commented on Ome/JavaScript/Assignment 13/JavaScriptAssignment13_Q2.html
> +
weekday = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"];

Done, made changes in array.

2021-05-06 11:03 UTC, omerana14 commented on Ome/JavaScript/Assignment 13/JavaScriptAssignment13_Q3.html
> +            var twoDaysAgo = d.getDate(x) - 2;  //change day here
function preDate() {
            var x = document.getElementById('chk_date').value;

            var date = new Date(x);
            var twoDaysAgo = date - 1000 * 60 * 60 * 24 * 2;   // current date's milliseconds - 1,000 ms * 60 s * 60 mins * 24 hrs * (# of days beyond one to go back)
            twoDaysAgo = new Date(twoDaysAgo);
            alert("Two day's ago date is : " + twoDaysAgo);
        }

I used here this logic, is it work?

2021-05-10 09:49 UTC, Snehal-113 approved these changes

2021-05-10 14:26 UTC, merged