Js assignment 10, 15
Pawan1005/MI-10-MEAN pull request #284
Opened 2021-05-05 07:15 UTC by sanketmod

2021-05-05 09:58 UTC, MKadeer17 approved these changes

2021-05-05 13:20 UTC, Snehal-113 requested changes

2021-05-05 13:20 UTC, Snehal-113 commented on sanket/javascript/assignment10(day28)/sanketA10_Q5.html
> +        document.write("number of words: " + newString.split(" ").length);
instead of document.write use a p tag and set the innerhtml for it.
this is an advice, u can merge this code

2021-05-05 13:20 UTC, Snehal-113 commented on sanket/javascript/assignment10(day28)/sanketA10_Q8.html
> +        let regExp = /[\w-]/;
not working as expected , even if there is no _ or - still it says the string has underscorre and dash

2021-05-06 04:37 UTC, poonam-khode approved these changes

2021-05-10 10:39 UTC, Snehal-113 approved these changes

2021-05-10 11:27 UTC, merged