Js assignment 20, 21.
Pawan1005/MI-10-MEAN pull request #294
Opened 2021-05-13 04:03 UTC by sanketmod

2021-05-13 05:48 UTC, MKadeer17 approved these changes

2021-05-13 05:48 UTC, MKadeer17 commented on sanket/javascript/assignment21(day33)/sanketA21_Q2.html
> +    <button>Edit</button>
Implement this Edit and Delete Button Logic also.

2021-05-13 17:37 UTC, Snehal-113 requested changes

2021-05-13 17:37 UTC, Snehal-113 commented on sanket/javascript/assignment21(day33)/sanketA21_Q2.html
> +</html>
checkboxes are disabled, edit and delete functionality nt working
also add functionality nt working properly

2021-05-17 06:09 UTC, poonam-khode approved these changes

2021-05-20 02:22 UTC, Snehal-113 approved these changes

2021-05-20 05:16 UTC, merged