Assignment 17 19 20 21
Pawan1005/MI-10-MEAN pull request #302
Opened 2021-05-19 05:53 UTC by priyaughade

2021-05-19 06:24 UTC, MKadeer17 approved these changes

2021-05-20 02:54 UTC, Snehal-113 requested changes

2021-05-20 02:54 UTC, Snehal-113 commented on priya/javascript/Assignment17/JsAssign17Q1.html
> +        var upper_name = name.toUpperCase();
name shld be converted in uppercase n displayed in the textbox also

2021-05-20 02:54 UTC, Snehal-113 commented on priya/javascript/Assignment17/JsAssign17Q1.html
> +          math = parseInt(prompt("enter marks again"));
don't use prompt..instead place the cursor in the text field where the marks are alphanumeric and try to use exception handling

2021-05-20 02:54 UTC, Snehal-113 commented on priya/javascript/Assignment17/JsAssign17Q2.html
> +</html>
make same changes suggested in ques 1, rest the program works well

2021-05-20 05:36 UTC, poonam-khode approved these changes

2021-05-24 11:32 UTC, Snehal-113 approved these changes

2021-05-24 11:33 UTC, merged