uploading day2 assignment
Pawan1005/MI-10-MEAN pull request #70
Opened 2021-02-17 09:04 UTC by Mrunali2997

2021-02-17 09:08 UTC, Snehapadvi96 approved these changes

2021-02-17 09:12 UTC, priyaughade approved these changes

2021-02-17 09:16 UTC, pratikshaghule approved these changes

2021-02-17 10:18 UTC, Pawan1005 requested changes

2021-02-17 10:18 UTC, Pawan1005 commented on mrunali/HTML/Day2-Assignment.html
> +</html>
remove extra space 
add new line at end

2021-02-18 07:14 UTC, pratikshaghule approved these changes

2021-02-18 09:07 UTC, Pawan1005 approved these changes

2021-02-18 09:08 UTC, merged