uploading day2 assignment
Pawan1005/MI-10-MEAN pull request #71
Opened 2021-02-17 09:20 UTC by Snehapadvi96

2021-02-17 09:22 UTC, Mrunali2997 approved these changes

2021-02-17 10:15 UTC, Pawan1005 requested changes

2021-02-17 10:15 UTC, Pawan1005 commented on Sneha/html/day1.html
> +</html>
make 4 separate files

2021-02-17 10:15 UTC, Pawan1005 commented on Sneha/html/day2.html
> +
remove extra lines

2021-02-17 10:15 UTC, Pawan1005 commented on Sneha/html/day2.html
> +
remove extra lines

2021-02-17 10:15 UTC, Pawan1005 commented on Sneha/html/day2.html
> +
remove extra lines

2021-02-17 10:15 UTC, Pawan1005 commented on Sneha/html/day2.html
> +</html>
need indentation 
remove extra spaces and lines

2021-02-18 11:48 UTC, nikitadamale97 approved these changes

2021-02-24 20:00 UTC, closed without merging