Create Assignment2.html
Pawan1005/MI-10-MEAN pull request #72
Opened 2021-02-17 09:24 UTC by pdukarande

<!DOCTYPE html>
<html>
    <head>
        <title>
            Formatting tags
        </title>
        <style>
            body {
                background-color: rgb(219, 102, 60);
            }
        </style>

    </head>
    <body>
        <h1><b>
                <center>Google</center>
        </b></h1>
        <h5><i>
            This article is about the company.
         </i></h5>
         <h2><b>
             From the garage to the Googleplex
         </b></h2>
         <p>This Google story is begins in 1995 at <strong> Standard University.</strong><br><i>Larry Page</i> was considering Standard for grad school and <strong><b>Sergey Brin,</b></strong>a student <br>there,was assigned to show him around.
            </p>
    <p>By some accounts, they disagreed about nearly everything during that first meeting,but by the following year they sruck a<span style="background-color: yellow;"> partnership.</span> <br>Working from their dorm rooms,they built a search engine that used links to determine the importance of
        individual pages on the <strong style="color: blueviolet;">World Wide Web.</strong></p><br>They called this search engine<span style="background-color: skyblue;"> <i>Backrub.</i></span>
        <hr>

        <h2><b>Initial public offering</b></h2>
      <p>Google's initial public offering(IPO) took place five years later,on 9th August 2004.<br>At that time Lary Page,Sergey Brin and eic Schmidt agreed to work together at Google for 30<u>20</u>
        </p>
        <b><center style="color:green;">Thank you!!</center></b>

    </body>

</html>

2021-02-17 10:13 UTC, Pawan1005 requested changes
check file before pushing on GitHub

2021-02-23 05:27 UTC, pdukarande commented
<!DOCTYPE html>
<html>
    <head>
        <title>Assignment4</title>
    </head>

    <body>
        <h2 align="center">Colspan</h2><br>
        <table border="1" cellspacing="0" cellpadding="10" align="center">
            <h4 align="center">List of Books</h4>
            <tr>
                <th>Author</th>
                <th colspan="2">Book</th>
            </tr>

            <tr>
                <td>J.K.Rowling</td>
                <td>Harry Potter</td>
                <td>Harry Potter 2</td>
            </tr>

            <tr>
                <td>Budyard Kapling</td>
                <td>Jungle Book</td>
                <td>Jungle Book 2</td>
            </tr>

        </table>


        <h2 align="center">Rowspan</h2><br>
        <table border="1" cellspacing="0" cellpadding="10" align="center">
            <h4 align="center">List of Books</h4>
            <tr>
                <th>Author</th>
                <td>APJ Abdul Kalam</td></th>
            </tr>

           

            <tr>
                <th rowspan="2" color="blue" align="center">Books</th>
                <td>Wings of fire</td>
            </tr>

            <tr>
                <td>Ignited Minds</td>
            </tr>

          
        </table>
    </body>
</html>

2021-02-26 07:13 UTC, Pawan1005 requested changes

2021-02-26 07:13 UTC, Pawan1005 commented on Piyush/HTML/Assignment2.html
> +
where is assignment

2021-03-15 10:37 UTC, closed without merging