Dnyaneshwar html file
Pawan1005/MI-10-MEAN pull request #76
Opened 2021-02-17 10:36 UTC by dnyaneshwarkhule

complete my task added my file

2021-02-17 14:25 UTC, Pawan1005 requested changes
please make sure all files

2021-02-22 06:20 UTC, Pawan1005 requested changes
make indentation properly in every file 
remove extra line

2021-02-22 06:20 UTC, Pawan1005 commented on dnyaneshwar k/mi mean.html
> +    </body>
check file is correct or not before pushing on git hub

2021-02-22 07:02 UTC, dnyaneshwarkhule commented
Ok sir

On Mon, Feb 22, 2021, 11:51 AM Pawan Jagtap <notifications@github.com>
wrote:

> *@Pawan1005* requested changes on this pull request.
>
> make indentation properly in every file
> remove extra line
> ------------------------------
>
> In dnyaneshwar k/mi mean.html
> <https://github.com/Pawan1005/MI-10-MEAN/pull/76#discussion_r580007067>:
>
> > @@ -0,0 +1,14 @@
> +<!DOYTYPE>
> +
> +    <html>
> +
> +    <head>
> +
> +        <titile> MI-MEAN9 </titile>
> +    </head>
> +
> +    <body>
> +        there are 4 member in my batch including me
> +
> +
> +    </body>
>
> check file is correct or not before pushing on git hub
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Pawan1005/MI-10-MEAN/pull/76#pullrequestreview-595036634>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARJMFIQEJFTFEYSSTQ3CAOLTAHZV3ANCNFSM4XYDH7EQ>
> .
>

2021-02-23 03:45 UTC, MKadeer17 approved these changes

2021-02-23 03:49 UTC, MKadeer17 commented on dnyaneshwar k/dnyaneshwarA3_1.html
> +
Order list comes in body tag not outside the body tag.

2021-02-23 03:49 UTC, MKadeer17 commented on dnyaneshwar k/mi mean.html
> +    </body>
closing html tag missing.

2021-03-15 10:37 UTC, closed without merging