uploading html webpage/komal1/html/komalA3_Q1.html into branch komal_…
Pawan1005/MI-10-MEAN pull request #81
Opened 2021-02-18 07:38 UTC by komal453

…work

2021-02-18 07:48 UTC, vishwaraj1706 reviewed
Place MI-MEAN before MI-MEAN-6

2021-02-18 09:47 UTC, Pawan1005 requested changes

2021-02-18 09:47 UTC, Pawan1005 commented on komal1/html/komalA3_Q2/home.html
> +
body tad missing 
remove extra lines 
add new line at the end

2021-02-18 09:47 UTC, Pawan1005 requested changes
every single file is missing with body tag

2021-02-22 08:04 UTC, Pawan1005 approved these changes

2021-02-22 08:12 UTC, merged